name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pedrovsc4
          password: Boavista3@

      - name: Build User Service Docker Image
        run: |
          docker build -t pedrovsc4/user-service-repo:latest ./services/user-service

      - name: Push User Service Docker Image to Docker Hub
        run: |
          docker push pedrovsc4/user-service-repo:latest

      - name: Build Order Service Docker Image
        run: |
          docker build -t pedrovsc4/order-service-repo:latest ./services/order-service

      - name: Push Order Service Docker Image to Docker Hub
        run: |
          docker push pedrovsc4/order-service-repo:latest

      - name: Build Product Service Docker Image
        run: |
          docker build -t pedrovsc4/product-service-repo:latest ./services/product-service

      - name: Push Product Service Docker Image to Docker Hub
        run: |
          docker push pedrovsc4/product-service-repo:latest

